INSERT INTO role(id, nome) VALUES ('1','ROLE_ASS');
INSERT INTO role(id, nome) VALUES ('2','ROLE_PESQUISA');
INSERT INTO role(id, nome) VALUES ('3','ROLE_ADMIN');
INSERT INTO usuario(id, nome, email, senha) VALUES ('1','admin','admin@email.com','admin');
INSERT INTO usuario(id, nome, email, senha) VALUES ('2','pesquisa','pesquisa@email.com','pesquisa');
INSERT INTO usuario(id, nome, email, senha) VALUES ('3','haylson','haylson@gmail.com','haylson');
INSERT INTO usuario(id, nome, email, senha) VALUES ('4','deyse','deyse@email.com','deyse');
INSERT INTO usuario(id, nome, email, senha) VALUES ('5','thaiane','thaiane@email.com','thaiane');
INSERT INTO usuario(id, nome, email, senha) VALUES ('6','andreia','andreia@email.com','andreia');
INSERT INTO usuario(id, nome, email, senha) VALUES ('7','klivia','klivia@email.com','klivia');
INSERT INTO usuario(id, nome, email, senha) VALUES ('8','teste','teste@email.com','$2a$10$I40AhJcJw55gHDUkjooCKuC84BnAJyzMRcuejG4G3CoouoX22Mzti');
INSERT INTO usuario_roles(usuario_id, roles_id) VALUES ('1','3');
INSERT INTO usuario_roles(usuario_id, roles_id) VALUES ('2','2');
INSERT INTO usuario_roles(usuario_id, roles_id) VALUES ('3','1');
INSERT INTO usuario_roles(usuario_id, roles_id) VALUES ('4','1');
INSERT INTO usuario_roles(usuario_id, roles_id) VALUES ('5','1');
INSERT INTO usuario_roles(usuario_id, roles_id) VALUES ('6','1');
INSERT INTO usuario_roles(usuario_id, roles_id) VALUES ('7','1');
INSERT INTO usuario_roles(usuario_id, roles_id) VALUES ('8','1');