package com.acre.ciu.model;

public enum EspecificidadeSocial {
	
	SITUACAO_RUA,
	QUILOMBOLA,
	RIBEIRINHA,
	CIGANA,
	INDIGENA_RESIDENTE_ALDEIA,
	INDIGENA_NAO_RESIDENTE_ALDEIA,
	FAMILIA_POR_AFINIDADE,
	FAMILIA_AMPLIADA,
	FAMILIA_NUCLEAR_CHEFE_MAE,
	FAMILIA_NUCLEAR_CHEFE_PAI,
	FAMILIA_MONOPARENTAL_CHEFE_MULHER,
	FAMILIA_MONOPARENTAL_CHEFE_HOMEM,
	NENHUMA_ANTERIORES

}
